#!/bin/bash

source ./.githooks/tests.sh

protected_branch="main"

bockPush() {
  echo "❌ Direct push to '$1' branch is not allowed."
  echo "🔒 This branch is protected. Please open a pull request instead."
  exit 1
}

while read local_ref local_sha remote_ref remote_sha
do
  branch_name=$(echo "$remote_ref" | sed 's|refs/heads/||')

  if [ "$branch_name" = "$protected_branch" ]; then
    bockPush $protected_branch
  else
    if ! checkDocker || ! checkDockerCompose; then
      echo "❌ Pre-push checks failed. Please fix the issues before pushing your changes."
      exit 1
    fi
    cleanImages
    echo "✅ Pre-push checks completed for branch '$branch_name'."
  fi
done

exit 0
