services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: notflix-backend
    container_name: notflix-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DEBUG=True
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0:8000" 
