.PHONY: all clean fclean re down restart
.SILENT:

# **************************************************************************** #
#                                   Variable                                   #
# **************************************************************************** #

NAME	= notflix
DC		= docker compose

# **************************************************************************** #
#                                    Sources                                   #
# **************************************************************************** #

COMPOSE_FILE	= docker-compose.dev.yml

# **************************************************************************** #
#                                     Rules                                    #
# **************************************************************************** #

all: $(NAME)

$(NAME): $(VOLUMES_DIR)
	$(DC) -f $(COMPOSE_FILE) up --build -d

down:
	$(DC) -f $(COMPOSE_FILE) down

restart: down all

clean:
	$(DC) -f $(COMPOSE_FILE) down --volumes --rmi all

fclean: clean
	docker system prune --force --all
	docker build -t python:3.13.5-alpine3.22 -f backend/Dockerfile-legrend .

re: fclean all
